{
  "seleniumLog": [],
  "checkPoints": [],
  "errorTrace": "java.lang.RuntimeException: com.qmetry.qaf.automation.testng.DataProviderException: Error while fetching data from resources/data/data.csv\r\n\tat org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)\r\n\tat org.testng.internal.Parameters.handleParameters(Parameters.java:429)\r\n\tat org.testng.internal.Invoker.handleParameters(Invoker.java:1383)\r\n\tat org.testng.internal.Invoker.createParameters(Invoker.java:1075)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:595)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:334)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:240)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1149)\r\n\tat org.testng.TestNG.run(TestNG.java:1057)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)\r\nCaused by: com.qmetry.qaf.automation.testng.DataProviderException: Error while fetching data from resources/data/data.csv\r\n\tat com.qmetry.qaf.automation.util.CSVUtil.getCSVDataAsMap(CSVUtil.java:186)\r\n\tat com.qmetry.qaf.automation.testng.pro.DataProviderUtil.getCSVData(DataProviderUtil.java:200)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)\r\n\t... 20 more\r\nCaused by: java.io.FileNotFoundException: resources\\data\\data.csv (The system cannot find the path specified)\r\n\tat java.io.FileInputStream.open0(Native Method)\r\n\tat java.io.FileInputStream.open(Unknown Source)\r\n\tat java.io.FileInputStream.<init>(Unknown Source)\r\n\tat java.io.FileReader.<init>(Unknown Source)\r\n\tat com.qmetry.qaf.automation.util.CSVUtil.getCSVDataAsMap(CSVUtil.java:152)\r\n\t... 27 more\r\n"
}